version: "2"

services: 
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    volumes:
      - ./src/main/resources/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      rlsx:
    ports:
      - 3306:3306
  app:
    image: greggu/rlsx-app:0.1
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=demo
      - DB_USER=demo
      - DB_PASSWORD=demo
      - DB_HOST=db
    networks:
      rlsx:
    ports:
      - "8080:8080"

networks:
  rlsx:
